### ISSUE TITLE
A few ideas on extra places to put downlod buttons

### ISSUE THREAD

**Issue by eightyy8** [Kawaizombi/kawai-scripts#41]
a download button should show when right-clicking on the options of any song
![firefox_gt7QHqBH4F](https://user-images.githubusercontent.com/64216434/129372950-a19de617-4e67-4a7f-bc0d-32d3ac7d4b3f.png)
also an option to download the whole playlist on the page, as well as on the options when right-clicking on the preview from the playlist
![firefox_Ijat1CkwFD](https://user-images.githubusercontent.com/64216434/129373645-296df292-b472-448c-9c7b-9bc3139a3c7e.png)
and in the downloader settings you should have the choice to change the file type of mp3 (mov, wav.. etc)

**Comment by Kawaizombi** [comment]
Thank you for your feedback

> a download button should show when right-clicking on the options of any song
This menu created/removed dynamically by soundcloud app, it's very hard to do because of that(it will also require time and effort to maintain such complex solution)

> and in the downloader settings you should have the choice to change the file type of mp3 (mov, wav.. etc)
File type convert cannot be done inside browser(I don't want to use any 3rd party online service to do convert on the fly, to keep script pure browser implementation)
